DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS bpm;
DROP TABLE IF EXISTS theme;
DROP TABLE IF EXISTS steps;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE temperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE bpm (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE steps (
  timestamp TIMESTAMP PRIMARY KEY NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value INTEGER NOT NULL,
  distance REAL NOT NULL
);

CREATE TABLE theme (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  changed_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  mode TEXT NOT NULL
);

INSERT INTO theme (mode)
VALUES ('light');